name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirments.txt

      - name: Run unit tests
        run: |
          pytest tests/

  deploy:
    name: Deploy to Railway
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Railway CLI
        run: |
          curl -fsSL https://railway.app/install.sh | sh
          export PATH="$HOME/.railway/bin:$PATH"

      # Установка Railway API токена в переменные окружения
      - name: Set Railway API Token
        run: echo "RAILWAY_API_TOKEN=${{ secrets.RAILWAY_API_TOKEN }}" >> $GITHUB_ENV

      # Связать проект с Railway (если это необходимо)
      - name: Link Railway Project
        run: |
          export RAILWAY_API_TOKEN=${{ secrets.RAILWAY_API_TOKEN }}
          railway link --project 60103c6e-f49d-4f29-9a57-7c6206311869 --service 4fce0a70-1016-4db7-b68f-ea8b1c8b8474 --no-input

      # Выполнение деплоя
      - name: Run Railway Command (Deploy)
        run: |
          export RAILWAY_API_TOKEN=${{ secrets.RAILWAY_API_TOKEN }}
          railway up --no-input
